spring:
  neo4j:
    uri: ${NE04J_URL:bolt://localhost:7687}
    authentication:
      username: ${NEO4_USER:neo4j}
      password: ${NEO4J_PASS:!J88FY&k^J##lAn}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_URL:https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com}
          issuer-uri: ${ISSUER_URL:https://securetoken.google.com/refgraph-11ae5}

